<a href="https://colab.research.google.com/github/zeglami/AI_Algorithms/blob/main/SpamDtector_Naive_Byses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Description spam detector 

In [3]:
#import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string 

In [4]:
#Load data
from google.colab import  files
uploaded= files.upload()

Saving emails.csv to emails.csv


In [5]:
#Read csv files
df=pd.read_csv('emails.csv')
#Print the fisrt row
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [6]:
#print the shap(nb of columns and rows)
df.shape

(5728, 2)

In [7]:
#get  the columns names
df.columns


Index(['text', 'spam'], dtype='object')

In [8]:
#Check of duplicates and remove them
df.drop_duplicates(inplace=True)

In [9]:
#Show the new shape (nb of columns and rows)
df.shape

(5695, 2)

In [10]:
#show the number of missing(NaN,NAN,na) data for each column
df.isnull().sum()


text    0
spam    0
dtype: int64

In [11]:
#download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [13]:
def process_text(text):
  #1 remove ponctuation
  #2 remove stopwords
  #3 return a list of clean words

  #1
  nopunc=[char for char in text if char not in string.punctuation ]
  nopunc=''.join(nopunc)
  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
  #3
  return clean_words


In [14]:
#Show the tokenization(a list of tokens also lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [15]:
    def fit_transform1(self, raw_documents, y=None):
        """Learn the vocabulary dictionary and return document-term matrix.
        This is equivalent to fit followed by transform, but more efficiently
        implemented.
        Parameters
        ----------
        raw_documents : iterable
            An iterable which yields either str, unicode or file objects.
        Returns
        -------
        X : array of shape (n_samples, n_features)
            Document-term matrix.
        """
        # We intentionally don't call the transform method to make
        # fit_transform overridable without unwanted side effects in
        # TfidfVectorizer.
        if isinstance(raw_documents, str):
            raise ValueError(
                "Iterable over raw text documents expected, "
                "string object received.")

        self._validate_params()
        self._validate_vocabulary()
        max_df = self.max_df
        min_df = self.min_df
        max_features = self.max_features

        vocabulary, X = self._count_vocab(raw_documents,
                                          self.fixed_vocabulary_)

        if self.binary:
            X.data.fill(1)

        if not self.fixed_vocabulary_:
            n_doc = X.shape[0]
            max_doc_count = (max_df
                             if isinstance(max_df, numbers.Integral)
                             else max_df * n_doc)
            min_doc_count = (min_df
                             if isinstance(min_df, numbers.Integral)
                             else min_df * n_doc)
            if max_doc_count < min_doc_count:
                raise ValueError(
                    "max_df corresponds to < documents than min_df")
            if max_features is not None:
                X = self._sort_features(X, vocabulary)
            X, self.stop_words_ = self._limit_features(X, vocabulary,
                                                       max_doc_count,
                                                       min_doc_count,
                                                       max_features)
            if max_features is None:
                X = self._sort_features(X, vocabulary)
            self.vocabulary_ = vocabulary

        return X

In [16]:
#Example
message4='hello world hello  hello world play'
message5='test test test test one  hello'

#Convert the text to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer 
bow4=CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print("bow4")
print(bow4)
print("bow4.shape")
print(bow4.shape)

bow4
  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1
bow4.shape
(2, 5)


In [17]:
#Convert a collection of text to matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer 
message_bow=CountVectorizer(analyzer=process_text).fit_transform(df['text'])
print(message_bow)

  (0, 3638)	1
  (0, 23369)	1
  (0, 18841)	1
  (0, 10065)	1
  (0, 17696)	1
  (0, 21140)	1
  (0, 27986)	1
  (0, 16674)	1
  (0, 28110)	1
  (0, 9296)	3
  (0, 21654)	2
  (0, 15429)	1
  (0, 32602)	1
  (0, 18238)	1
  (0, 18886)	1
  (0, 16089)	2
  (0, 8054)	1
  (0, 20952)	3
  (0, 32319)	1
  (0, 31968)	1
  (0, 24838)	1
  (0, 36025)	2
  (0, 21431)	2
  (0, 33037)	1
  (0, 23040)	2
  :	:
  (5694, 24818)	2
  (5694, 21624)	1
  (5694, 5729)	9
  (5694, 30934)	1
  (5694, 2828)	3
  (5694, 13338)	1
  (5694, 13127)	1
  (5694, 17388)	1
  (5694, 14130)	1
  (5694, 20273)	1
  (5694, 31827)	1
  (5694, 13128)	1
  (5694, 20467)	1
  (5694, 35288)	1
  (5694, 8629)	1
  (5694, 30082)	1
  (5694, 13522)	5
  (5694, 36185)	1
  (5694, 959)	2
  (5694, 2797)	1
  (5694, 30287)	1
  (5694, 17590)	1
  (5694, 33923)	1
  (5694, 10373)	1
  (5694, 11386)	1


In [ ]:
#split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(message_bow,df['spam'],test_size=0.20,random_state=0)


In [ ]:
#get the shape of the date
message_bow.shape

(5695, 37229)

In [ ]:
#Create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train,y_train)

In [ ]:
#Print the pedictions
print(classifier.predict(X_train))
#Print the actual values
print(y_train.values)


[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [ ]:
#Evalute the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_train)
print(classification_report(y_train,pred))
print()
print('Confusion matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy:',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion matrix: 
 [[3445   12]
 [   1 1098]]

Accuracy: 0.9971466198419666


In [ ]:
#Print the pedictions
print(classifier.predict(X_test))
#Print the actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [ ]:
#Evalute the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
pred=classifier.predict(X_test)
print(classification_report(y_test,pred))
print()
print('Confusion matrix: \n',confusion_matrix(y_test,pred))
print()
print('Accuracy:',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion matrix: 
 [[862   8]
 [  1 268]]

Accuracy: 0.9920983318700615
